2024-05-28 12:54:54,398 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094047, 'message': {'message_id': 271, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890094, 'text': 'Citesc. Bot este bine. Foarte bine'}}]`
2024-05-28 12:54:54,399 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094047]
2024-05-28 12:54:54,399 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 9, 54, 54, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, message_id=271, supergroup_chat_created=False, text='Citesc. Bot este bine. Foarte bine'), update_id=440094047)
2024-05-28 12:54:54,400 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094047]
2024-05-28 12:54:54,400 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094047]
2024-05-28 12:54:54,400 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094048}`
2024-05-28 12:54:54,405 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094047], language detect
2024-05-28 12:54:54,406 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094047], sentences extract
2024-05-28 12:54:54,406 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate gcloud begin [440094047]
2024-05-28 12:54:54,511 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator ERROR
	translate gcloud exception [440094047]
Traceback (most recent call last):
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.186.42:443 {grpc_message:"Invalid field \"labels.username\"; value \"AnnDorosheva\" does not conform to regular expression \"[\\p{Ll}\\p{Lo}\\p{N}_-]{0,63}\"; character \"A\" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore", grpc_status:3, created_time:"2024-05-28T12:54:54.510274008+03:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladpy/projects/telegram-ro-bot/src/vladpy_telegram_ro_bot/_application/_translator/_translator.py", line 252, in __translate_gcloud
    await self.__gtranslate_client.translate_text(
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/cloud/translate_v3/services/translation_service/async_client.py", line 472, in translate_text
    response = await rpc(
               ^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:54:54,515 P4686|T140697370851136
	vladpy_telegram_ro_bot.Application ERROR
	application error: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:55:00,338 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094048, 'message': {'message_id': 272, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890100, 'text': '/hello', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}]`
2024-05-28 12:55:00,338 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094048]
2024-05-28 12:55:00,339 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 9, 55, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, message_id=272, supergroup_chat_created=False, text='/hello'), update_id=440094048)
2024-05-28 12:55:00,339 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	command handle begin [440094048]
2024-05-28 12:55:00,339 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	command handle "hello" [440094048]
2024-05-28 12:55:00,339 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Passing request through rate limiter of type <class 'telegram.ext._aioratelimiter.AIORateLimiter'> with rate_limit_args None
2024-05-28 12:55:00,339 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `sendMessage` with parameters `{'chat_id': -4267387862, 'text': 'Hello\\. This is Romanian translator Bot\\. Please, send me romanian text and I will translate it for you, sentence by sentence\\.', 'parse_mode': <ParseMode.MARKDOWN_V2>, 'reply_parameters': ReplyParameters(message_id=272, quote_parse_mode=<ParseMode.MARKDOWN_V2>)}`
2024-05-28 12:55:00,340 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094049}`
2024-05-28 12:55:00,747 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `sendMessage` finished with return value `{'message_id': 273, 'from': {'id': 7000320864, 'is_bot': True, 'first_name': 'RoBot', 'username': 'vladpy_ro_bot'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890100, 'reply_to_message': {'message_id': 272, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890100, 'text': '/hello', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}, 'text': 'Hello. This is Romanian translator Bot. Please, send me romanian text and I will translate it for you, sentence by sentence.'}`
2024-05-28 12:55:00,748 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	command handle end [440094048]
2024-05-28 12:55:10,476 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[]`
2024-05-28 12:55:10,476 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.






2024-05-28 12:55:50,924 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.
2024-05-28 12:55:50,924 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094049}`
2024-05-28 12:55:59,833 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094049, 'message': {'message_id': 274, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890159, 'forward_origin': {'type': 'user', 'sender_user': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'date': 1716890094}, 'forward_from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'forward_date': 1716890094, 'text': 'Citesc. Bot este bine. Foarte bine'}}]`
2024-05-28 12:55:59,833 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094049]
2024-05-28 12:55:59,833 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(api_kwargs={'forward_date': 1716890094, 'forward_from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}}, channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 9, 55, 59, tzinfo=<UTC>), delete_chat_photo=False, forward_origin=MessageOriginUser(date=datetime.datetime(2024, 5, 28, 9, 54, 54, tzinfo=<UTC>), sender_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), type=<MessageOriginType.USER>), from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, message_id=274, supergroup_chat_created=False, text='Citesc. Bot este bine. Foarte bine'), update_id=440094049)
2024-05-28 12:55:59,834 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094049]
2024-05-28 12:55:59,834 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094049]
2024-05-28 12:55:59,834 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094050}`
2024-05-28 12:55:59,840 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094049], language detect
2024-05-28 12:55:59,841 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094049], sentences extract
2024-05-28 12:55:59,841 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate gcloud begin [440094049]
2024-05-28 12:55:59,942 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator ERROR
	translate gcloud exception [440094049]
Traceback (most recent call last):
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.186.42:443 {created_time:"2024-05-28T12:55:59.941954903+03:00", grpc_status:3, grpc_message:"Invalid field \"labels.username\"; value \"AnnDorosheva\" does not conform to regular expression \"[\\p{Ll}\\p{Lo}\\p{N}_-]{0,63}\"; character \"A\" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladpy/projects/telegram-ro-bot/src/vladpy_telegram_ro_bot/_application/_translator/_translator.py", line 252, in __translate_gcloud
    await self.__gtranslate_client.translate_text(
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/cloud/translate_v3/services/translation_service/async_client.py", line 472, in translate_text
    response = await rpc(
               ^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:55:59,942 P4686|T140697370851136
	vladpy_telegram_ro_bot.Application ERROR
	application error: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:56:09,970 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[]`
2024-05-28 12:56:09,971 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.
2024-05-28 12:56:09,971 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094050}`





2024-05-28 12:57:30,662 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094056}`
2024-05-28 12:57:36,089 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094056, 'message': {'message_id': 282, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890256, 'text': 'Eu Citesc. Bot este bine. Foarte bine'}}]`
2024-05-28 12:57:36,089 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094056]
2024-05-28 12:57:36,089 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 9, 57, 36, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, message_id=282, supergroup_chat_created=False, text='Eu Citesc. Bot este bine. Foarte bine'), update_id=440094056)
2024-05-28 12:57:36,090 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094056]
2024-05-28 12:57:36,090 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094056]
2024-05-28 12:57:36,090 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094057}`
2024-05-28 12:57:36,095 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094056], language detect
2024-05-28 12:57:36,096 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094056], sentences extract
2024-05-28 12:57:36,096 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate gcloud begin [440094056]
2024-05-28 12:57:36,190 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator ERROR
	translate gcloud exception [440094056]
Traceback (most recent call last):
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.186.42:443 {created_time:"2024-05-28T12:57:36.190276169+03:00", grpc_status:3, grpc_message:"Invalid field \"labels.username\"; value \"AnnDorosheva\" does not conform to regular expression \"[\\p{Ll}\\p{Lo}\\p{N}_-]{0,63}\"; character \"A\" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladpy/projects/telegram-ro-bot/src/vladpy_telegram_ro_bot/_application/_translator/_translator.py", line 252, in __translate_gcloud
    await self.__gtranslate_client.translate_text(
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/cloud/translate_v3/services/translation_service/async_client.py", line 472, in translate_text
    response = await rpc(
               ^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:57:36,191 P4686|T140697370851136
	vladpy_telegram_ro_bot.Application ERROR
	application error: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:57:46,226 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[]`
2024-05-28 12:57:46,227 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.





2024-05-28 12:59:11,731 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[]`
2024-05-28 12:59:11,731 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.
2024-05-28 12:59:11,731 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094065}`
2024-05-28 12:59:16,441 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094065, 'message': {'message_id': 292, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890356, 'text': 'Cițeşc'}}]`
2024-05-28 12:59:16,441 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094065]
2024-05-28 12:59:16,442 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 9, 59, 16, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, message_id=292, supergroup_chat_created=False, text='Cițeşc'), update_id=440094065)
2024-05-28 12:59:16,442 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094065]
2024-05-28 12:59:16,442 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094065]
2024-05-28 12:59:16,442 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094066}`
2024-05-28 12:59:16,444 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094065], language detect
2024-05-28 12:59:16,445 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094065], sentences extract
2024-05-28 12:59:16,445 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate gcloud begin [440094065]
2024-05-28 12:59:16,748 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator ERROR
	translate gcloud exception [440094065]
Traceback (most recent call last):
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.186.42:443 {created_time:"2024-05-28T12:59:16.748097676+03:00", grpc_status:3, grpc_message:"Invalid field \"labels.username\"; value \"AnnDorosheva\" does not conform to regular expression \"[\\p{Ll}\\p{Lo}\\p{N}_-]{0,63}\"; character \"A\" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladpy/projects/telegram-ro-bot/src/vladpy_telegram_ro_bot/_application/_translator/_translator.py", line 252, in __translate_gcloud
    await self.__gtranslate_client.translate_text(
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/cloud/translate_v3/services/translation_service/async_client.py", line 472, in translate_text
    response = await rpc(
               ^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:59:16,748 P4686|T140697370851136
	vladpy_telegram_ro_bot.Application ERROR
	application error: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 12:59:21,459 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094066, 'message': {'message_id': 293, 'from': {'id': 507630489, 'is_bot': False, 'first_name': 'Vladislav', 'last_name': 'Pyslaru', 'username': 'vladpy', 'language_code': 'en'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890361, 'text': 'ну не'}}]`
2024-05-28 12:59:21,459 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094066]
2024-05-28 12:59:21,459 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 9, 59, 21, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Vladislav', id=507630489, is_bot=False, language_code='en', last_name='Pyslaru', username='vladpy'), group_chat_created=False, message_id=293, supergroup_chat_created=False, text='ну не'), update_id=440094066)
2024-05-28 12:59:21,459 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094066]
2024-05-28 12:59:21,460 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094066]








2024-05-28 13:05:43,311 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094074}`
2024-05-28 13:05:48,635 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094074, 'message': {'message_id': 301, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890748, 'text': 'Comanda a fost preluată\nNumărul comenzii dumneavoastră\n3\n4\n5\n6\n5\n7\n1\n2\nToată informația referitoare la comanda dumneavoastră a fost expediată pe poșta electronică indicată.\nVă recomandăm să consumați bucatele imediat după primirea comenzii.\nMulțumim că ați ales\nLa Plăcinte!\nÎnapoi la meniu', 'entities': [{'offset': 0, 'length': 23, 'type': 'bold'}, {'offset': 262, 'length': 12, 'type': 'bold'}, {'offset': 275, 'length': 15, 'type': 'text_link', 'url': 'https://laplacinte.md/ro'}], 'link_preview_options': {'url': 'https://laplacinte.md/ro', 'prefer_small_media': True}}}]`
2024-05-28 13:05:48,635 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094074]
2024-05-28 13:05:48,636 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 10, 5, 48, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=23, offset=0, type=<MessageEntityType.BOLD>), MessageEntity(length=12, offset=262, type=<MessageEntityType.BOLD>), MessageEntity(length=15, offset=275, type=<MessageEntityType.TEXT_LINK>, url='https://laplacinte.md/ro')), from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, link_preview_options=LinkPreviewOptions(prefer_small_media=True, url='https://laplacinte.md/ro'), message_id=301, supergroup_chat_created=False, text='Comanda a fost preluată\nNumărul comenzii dumneavoastră\n3\n4\n5\n6\n5\n7\n1\n2\nToată informația referitoare la comanda dumneavoastră a fost expediată pe poșta electronică indicată.\nVă recomandăm să consumați bucatele imediat după primirea comenzii.\nMulțumim că ați ales\nLa Plăcinte!\nÎnapoi la meniu'), update_id=440094074)
2024-05-28 13:05:48,636 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094074]
2024-05-28 13:05:48,636 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094074]
2024-05-28 13:05:48,636 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094075}`
2024-05-28 13:05:48,639 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094074], language detect
2024-05-28 13:05:48,640 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094074], sentences extract
2024-05-28 13:05:48,640 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate gcloud begin [440094074]
2024-05-28 13:05:48,872 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator ERROR
	translate gcloud exception [440094074]
Traceback (most recent call last):
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.181.234:443 {grpc_message:"Invalid field \"labels.username\"; value \"AnnDorosheva\" does not conform to regular expression \"[\\p{Ll}\\p{Lo}\\p{N}_-]{0,63}\"; character \"A\" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore", grpc_status:3, created_time:"2024-05-28T13:05:48.872209512+03:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladpy/projects/telegram-ro-bot/src/vladpy_telegram_ro_bot/_application/_translator/_translator.py", line 252, in __translate_gcloud
    await self.__gtranslate_client.translate_text(
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/cloud/translate_v3/services/translation_service/async_client.py", line 472, in translate_text
    response = await rpc(
               ^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 13:05:48,872 P4686|T140697370851136
	vladpy_telegram_ro_bot.Application ERROR
	application error: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 13:05:58,773 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[]`
2024-05-28 13:05:58,773 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.
2024-05-28 13:05:58,773 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094075}`
2024-05-28 13:06:00,411 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094075, 'message': {'message_id': 302, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890760, 'text': '/hello', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}}]`
2024-05-28 13:06:00,411 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094075]
2024-05-28 13:06:00,412 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 10, 6, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, message_id=302, supergroup_chat_created=False, text='/hello'), update_id=440094075)
2024-05-28 13:06:00,412 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	command handle begin [440094075]
2024-05-28 13:06:00,412 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	command handle "hello" [440094075]
2024-05-28 13:06:00,412 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Passing request through rate limiter of type <class 'telegram.ext._aioratelimiter.AIORateLimiter'> with rate_limit_args None
2024-05-28 13:06:00,412 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `sendMessage` with parameters `{'chat_id': -4267387862, 'text': 'Hello\\. This is Romanian translator Bot\\. Please, send me romanian text and I will translate it for you, sentence by sentence\\.', 'parse_mode': <ParseMode.MARKDOWN_V2>, 'reply_parameters': ReplyParameters(message_id=302, quote_parse_mode=<ParseMode.MARKDOWN_V2>)}`
2024-05-28 13:06:00,413 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094076}`
2024-05-28 13:06:00,622 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `sendMessage` finished with return value `{'message_id': 303, 'from': {'id': 7000320864, 'is_bot': True, 'first_name': 'RoBot', 'username': 'vladpy_ro_bot'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890760, 'reply_to_message': {'message_id': 302, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890760, 'text': '/hello', 'entities': [{'offset': 0, 'length': 6, 'type': 'bot_command'}]}, 'text': 'Hello. This is Romanian translator Bot. Please, send me romanian text and I will translate it for you, sentence by sentence.'}`
2024-05-28 13:06:00,623 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	command handle end [440094075]
2024-05-28 13:06:10,549 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[]`
2024-05-28 13:06:10,549 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	No new updates found.
2024-05-28 13:06:10,549 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094076}`
2024-05-28 13:06:10,595 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Call to Bot API endpoint `getUpdates` finished with return value `[{'update_id': 440094076, 'message': {'message_id': 304, 'from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'chat': {'id': -4267387862, 'title': 'RoBot Debug', 'type': 'group', 'all_members_are_administrators': True}, 'date': 1716890770, 'forward_origin': {'type': 'user', 'sender_user': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'date': 1716890748}, 'forward_from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}, 'forward_date': 1716890748, 'text': 'Comanda a fost preluată\nNumărul comenzii dumneavoastră\n3\n4\n5\n6\n5\n7\n1\n2\nToată informația referitoare la comanda dumneavoastră a fost expediată pe poșta electronică indicată.\nVă recomandăm să consumați bucatele imediat după primirea comenzii.\nMulțumim că ați ales\nLa Plăcinte!\nÎnapoi la meniu', 'entities': [{'offset': 0, 'length': 23, 'type': 'bold'}, {'offset': 262, 'length': 12, 'type': 'bold'}, {'offset': 275, 'length': 15, 'type': 'text_link', 'url': 'https://laplacinte.md/ro'}], 'link_preview_options': {'url': 'https://laplacinte.md/ro', 'prefer_small_media': True}}}]`
2024-05-28 13:06:10,595 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Getting updates: [440094076]
2024-05-28 13:06:10,595 P4686|T140697370851136
	telegram.ext.Application DEBUG
	Processing update Update(message=Message(api_kwargs={'forward_date': 1716890748, 'forward_from': {'id': 217555405, 'is_bot': False, 'first_name': 'Анна', 'last_name': 'Дорошева', 'username': 'AnnDorosheva'}}, channel_chat_created=False, chat=Chat(api_kwargs={'all_members_are_administrators': True}, id=-4267387862, title='RoBot Debug', type=<ChatType.GROUP>), date=datetime.datetime(2024, 5, 28, 10, 6, 10, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=23, offset=0, type=<MessageEntityType.BOLD>), MessageEntity(length=12, offset=262, type=<MessageEntityType.BOLD>), MessageEntity(length=15, offset=275, type=<MessageEntityType.TEXT_LINK>, url='https://laplacinte.md/ro')), forward_origin=MessageOriginUser(date=datetime.datetime(2024, 5, 28, 10, 5, 48, tzinfo=<UTC>), sender_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), type=<MessageOriginType.USER>), from_user=User(first_name='Анна', id=217555405, is_bot=False, last_name='Дорошева', username='AnnDorosheva'), group_chat_created=False, link_preview_options=LinkPreviewOptions(prefer_small_media=True, url='https://laplacinte.md/ro'), message_id=304, supergroup_chat_created=False, text='Comanda a fost preluată\nNumărul comenzii dumneavoastră\n3\n4\n5\n6\n5\n7\n1\n2\nToată informația referitoare la comanda dumneavoastră a fost expediată pe poșta electronică indicată.\nVă recomandăm să consumați bucatele imediat după primirea comenzii.\nMulțumim că ați ales\nLa Plăcinte!\nÎnapoi la meniu'), update_id=440094076)
2024-05-28 13:06:10,596 P4686|T140697370851136
	vladpy_telegram_ro_bot.Bot INFO
	translation handle begin [440094076]
2024-05-28 13:06:10,596 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate begin [440094076]
2024-05-28 13:06:10,596 P4686|T140697370851136
	telegram.ext.ExtBot DEBUG
	Calling Bot API endpoint `getUpdates` with parameters `{'timeout': 10, 'offset': 440094077}`
2024-05-28 13:06:10,599 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094076], language detect
2024-05-28 13:06:10,600 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate [440094076], sentences extract
2024-05-28 13:06:10,600 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator INFO
	translate gcloud begin [440094076]
2024-05-28 13:06:10,855 P4686|T140697370851136
	vladpy_telegram_ro_bot.Translator ERROR
	translate gcloud exception [440094076]
Traceback (most recent call last):
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/grpc/aio/_call.py", line 318, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore"
	debug_error_string = "UNKNOWN:Error received from peer ipv4:142.250.181.234:443 {grpc_message:"Invalid field \"labels.username\"; value \"AnnDorosheva\" does not conform to regular expression \"[\\p{Ll}\\p{Lo}\\p{N}_-]{0,63}\"; character \"A\" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore", grpc_status:3, created_time:"2024-05-28T13:06:10.855700871+03:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vladpy/projects/telegram-ro-bot/src/vladpy_telegram_ro_bot/_application/_translator/_translator.py", line 252, in __translate_gcloud
    await self.__gtranslate_client.translate_text(
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/cloud/translate_v3/services/translation_service/async_client.py", line 472, in translate_text
    response = await rpc(
               ^^^^^^^^^^
  File "/home/vladpy/miniconda3/envs/telegram-ro-bot/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore
2024-05-28 13:06:10,856 P4686|T140697370851136
	vladpy_telegram_ro_bot.Application ERROR
	application error: 400 Invalid field "labels.username"; value "AnnDorosheva" does not conform to regular expression "[\p{Ll}\p{Lo}\p{N}_-]{0,63}"; character "A" at position 0 is not a non-uppercased letter (Unicode character class Ll or Lo), digit, hyphen, or underscore

